
import java.util.LinkedList;

public class LanParser extends Parser {

    public LanParser(String prvNeterminal, LinkedList<Zeton> zetonte, int m,
            int n) {
        super(prvNeterminal, zetonte, m, n);
        terNeter();
        pravila();
        parseTable();
    }

    public void terNeter() {
        this.neTerminal("главна");
        this.neTerminal("остаток");
        this.neTerminal("аргументи");
        this.neTerminal("аргумент");
        this.neTerminal("аргументи2");
        this.neTerminal("команди");
        this.neTerminal("локални");
        this.neTerminal("локални1");
        this.neTerminal("локални2");
        this.neTerminal("иницијализација");
        this.neTerminal("иницирај");
        this.neTerminal("операција");
        this.neTerminal("основникоманди");
        this.neTerminal("контролникоманди");
        this.neTerminal("опција");
        this.neTerminal("блок");
        this.neTerminal("услов");
        this.neTerminal("условкоманда");
        this.neTerminal("повторувачкикоманди");
        this.neTerminal("повторува");
        this.neTerminal("опција1");
        this.neTerminal("нешто");
        this.neTerminal("параметри");
        this.neTerminal("параметри1");
        this.neTerminal("параметри2");
        this.neTerminal("параметрите");
        this.neTerminal("нешто2");
        this.neTerminal("знак");

        this.terminal("процедура");
        this.terminal("(");
        this.terminal(")");
        this.terminal("почеток");
        this.terminal("крај");
        this.terminal("насока");
        this.terminal("број");
        this.terminal("променлива");
        this.terminal("име");
        this.terminal("+");
        this.terminal("-");
        this.terminal("*");
        this.terminal("оди");
        this.terminal("свртиЛево");
        this.terminal("свртиДесно");
        this.terminal("земи");
        this.terminal("остави");
        this.terminal("ако");
        this.terminal("жетон");
        this.terminal("ѕид");
        this.terminal(",");
        this.terminal("!");
        this.terminal("телепорт");
        this.terminal("повторувај");
        this.terminal("до");
        this.terminal("==");
        this.terminal("<>");
        this.terminal(">");
        this.terminal("<");
        this.terminal(">=");
        this.terminal("<=");
        this.terminal("=");
        this.terminal("пати");
        this.terminal(":");


    }

    public void pravila() {
        //this.pravilata("главна процедура");
        this.pravilata("процедура остаток");
        this.pravilata("( ) почеток команди крај");
        this.pravilata("име ( аргументи ) почеток команди крај процедура остаток");
        this.pravilata("");
        this.pravilata("насока име аргумент");
        this.pravilata("број име аргумент");
        this.pravilata("");
        this.pravilata(", аргументи2");
        this.pravilata("број име аргумент");
        this.pravilata("насока име аргумент");
        this.pravilata("");
        this.pravilata("локални иницијализација команди");
        this.pravilata("променлива име локални1");
        this.pravilata("");
        this.pravilata(", локални2");
        this.pravilata("");
        this.pravilata("име локални1");
        this.pravilata("име знак");//
        this.pravilata("број");
        this.pravilata("насока");
        this.pravilata("");
        this.pravilata("+ број операција");//
        this.pravilata("- број операција");
        this.pravilata("* број операција");
        this.pravilata("");
        this.pravilata("основникоманди команди");
        this.pravilata("оди");
        this.pravilata("свртиЛево");
        this.pravilata("свртиДесно");
        this.pravilata("земи");
        this.pravilata("остави");
        this.pravilata("контролникоманди команди");
        this.pravilata("ако опција");
        this.pravilata("жетон блок");
        this.pravilata("ѕид блок");
        this.pravilata("насока блок");
        this.pravilata("( услов ) блок");
        this.pravilata("! команди !");
        this.pravilata("број условкоманда");
        this.pravilata("== број");
        this.pravilata("<> број");
        this.pravilata("> број");
        this.pravilata("< број");
        this.pravilata(">= број");
        this.pravilata("<= број");
        this.pravilata("повторувачкикоманди команди");
        this.pravilata("повторувај повторува");
        this.pravilata("број пати : блок");
        this.pravilata("до опција1");
        this.pravilata("жетон : блок");
        this.pravilata("( услов ) : блок");
        this.pravilata("ѕид : блок");
        this.pravilata("насока : блок");
        this.pravilata("телепорт ( параметрите ) команди");
        this.pravilata("( параметри )");
        this.pravilata("број параметри1");
        this.pravilata("насока параметри1");
        this.pravilata("име параметри1");
        this.pravilata("");
        this.pravilata("");
        this.pravilata(", параметри2");
        this.pravilata("број параметри1");
        this.pravilata("насока параметри1");
        this.pravilata("име параметри1");
        this.pravilata("број , број");
        this.pravilata("= нешто2");
        this.pravilata("име нешто команди");
        this.pravilata("број операција");
        this.pravilata("насока");
        this.pravilata("= иницирај иницијализација");
        this.pravilata("( параметри )");
        

    }

    public void parseTable() {
        this.tabela("главна", "процедура", 1);
        this.tabela("остаток", "(", 2);
        this.tabela("остаток", "име", 3);
        this.tabela("аргументи", ")", 4);
        this.tabela("аргументи", "насока", 5);
        this.tabela("аргументи", "број", 6);
        this.tabela("аргумент", ")", 7);
        this.tabela("аргумент", ",", 8);
        this.tabela("аргументи2", "насока", 10);
        this.tabela("аргументи2", "број", 9);
        this.tabela("команди", "крај", 11);
        this.tabela("команди", "променлива", 12);
        this.tabela("команди", "име", 67);
        this.tabela("команди", "оди", 26);
        this.tabela("команди", "свртиЛево", 26);
        this.tabela("команди", "свртиДесно", 26);
        this.tabela("команди", "земи", 26);
        this.tabela("команди", "остави", 26);
        this.tabela("команди", "ако", 32);
        this.tabela("команди", "!", 11);
        this.tabela("команди", "телепорт", 54);
        this.tabela("команди", "повторувај", 46);
        this.tabela("локални", "крај", 14);
        this.tabela("локални", "променлива", 13);
        this.tabela("локални", "име", 14);
        this.tabela("локални1", "крај", 16);
        this.tabela("локални1", "име", 16);
        this.tabela("локални1", ",", 15);
        this.tabela("локални2", "име", 17);
        this.tabela("иницијализација", "крај", 21);
        this.tabela("иницијализација", "променлива", 21);
        this.tabela("иницијализација", "име", 18);
        this.tabela("иницијализација", "оди", 21);
        this.tabela("иницијализација", "свртиЛево", 21);
        this.tabela("иницијализација", "свртиДесно", 21);
        this.tabela("иницијализација", "земи", 21);
        this.tabela("иницијализација", "остави", 21);
        this.tabela("иницијализација", "ако", 21);
        this.tabela("иницијализација", "телепорт", 21);
        this.tabela("иницијализација", "повторувај", 21);
        this.tabela("иницирај", "насока", 20);
        this.tabela("иницирај", "број", 19);
        this.tabela("операција", "име", 25);
        this.tabela("операција", "променлива", 25);
        this.tabela("операција", "оди", 25);
        this.tabela("операција", "свртиЛево", 25);
        this.tabela("операција", "свртиДесно", 25);
        this.tabela("операција", "земи", 25);
        this.tabela("операција", "остави", 25);
        this.tabela("операција", "ако", 25);
        this.tabela("операција", "повторувај", 25);
        this.tabela("операција", "телепорт", 25);
        this.tabela("операција", "крај", 25);
        this.tabela("операција", "!", 25);      
        this.tabela("операција", "+", 22);
        this.tabela("операција", "-", 23);
        this.tabela("операција", "*", 24);
        this.tabela("основникоманди", "оди", 27);
        this.tabela("основникоманди", "свртиЛево", 28);
        this.tabela("основникоманди", "свртиДесно", 29);
        this.tabela("основникоманди", "земи", 30);
        this.tabela("основникоманди", "остави", 31);
        this.tabela("контролникоманди", "ако", 33);
        this.tabela("опција", "(", 37);
        this.tabela("опција", "насока", 36);
        this.tabela("опција", "жетон", 34);
        this.tabela("опција", "ѕид", 35);
        this.tabela("блок", "!", 38);
        this.tabela("услов", "број", 39);
        this.tabela("условкоманда", "==", 40);
        this.tabela("условкоманда", "<>", 41);
        this.tabela("условкоманда", ">", 42);
        this.tabela("условкоманда", "<", 43);
        this.tabela("условкоманда", ">=", 44);
        this.tabela("условкоманда", "<=", 45);
        this.tabela("повторувачкикоманди", "повторувај", 47);
        this.tabela("повторува", "број", 48);
        this.tabela("повторува", "до", 49);
        this.tabela("опција1", "(", 51);
        this.tabela("опција1", "насока", 53);
        this.tabela("опција1", "жетон", 50);
        this.tabela("опција1", "ѕид", 52);
        this.tabela("нешто", "(", 55);
        this.tabela("нешто", "=", 66);
        this.tabela("параметри", ")", 59);
        this.tabela("параметри", "насока", 57);
        this.tabela("параметри", "број", 56);
      //  this.tabela("параметри", "име", 58);
        this.tabela("параметри1", ")", 60);
        this.tabela("параметри1", ",", 61);
        this.tabela("параметри2", "насока", 63);
        this.tabela("параметри2", "број", 62);
       // this.tabela("параметри2", "име", 64);
        this.tabela("параметрите", "број", 65);
        this.tabela("нешто2", "број", 68);
        this.tabela("нешто2", "насока", 69);
        this.tabela("знак", "=", 70);
        this.tabela("знак", "(", 71);
    }
}
